# Generated by Django 3.2.5 on 2021-08-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210804_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
