# Generated by Django 3.2.5 on 2021-08-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210812_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='longitude',
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='retail_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
